services:
  db:
    image: mariadb:11
    container_name: prl-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./src/db/db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  nginx:
    image: nginx:latest
    container_name: prl-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src/frontend:/usr/share/nginx/html:ro