FROM python:3.12-slim

WORKDIR /app

COPY src/backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/backend .
COPY src/frontend ./frontend

EXPOSE 5000

CMD ["python", "app.py"]
