@startuml
actor User
participant Frontend
participant Backend
database Datenbank
participant YouTube

User -> Frontend: Seite öffnen
Frontend -> Backend: GET pig_stats
Backend -> Datenbank: GET pig_stats
Datenbank --> Backend: pig_stats
Backend -> Frontend: present pig_stats

User -> Frontend: Spiel starten und den Teilnehmern\n Schweine und Einsatz zuordnen
Frontend -> Backend: GET random_rennen
Backend -> Datenbank: GET random_rennen
Datenbank --> Backend: YT-URL + Timestamps

Backend --> Frontend: Startsignal für Rennen\n mit Video-Embed

    par Video abspielen
        Frontend -> YouTube: Play Race Video
        YouTube --> Frontend: Video-Stream
    else Rennen lokal auswerten
        Frontend -> Backend: Anfrage zur Gewinnerberechnung
        Backend -> Datenbank: Hole Renn-Ergebnis
        Datenbank --> Backend: Renn-Ergebnis
        Backend --> Frontend: Renn-Ergebnis
        Frontend -> Frontend: Bestimme Gewinner
    end

Frontend --> User: Anzeige Gewinner + Belohnung
@enduml